/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jnitest_Jni */

#ifndef _Included_com_example_jnitest_Jni
#define _Included_com_example_jnitest_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jnitest_Jni
 * Method:    say
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jnitest_Jni_say
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
